EXTS = {
    ".abc": "fbxreview",
    ".blend": "blender",
    ".fbx": "fbxreview",
    ".kra": "krita",
    ".hip": "houdini",
    ".hipnc": "houdini",
    ".ma": "maya",
    ".mb": "maya",
    ".nk": "nuke",
    ".obj": "fbxreview",
    ".psd": "photoshop",
    ".drp": "resolve",
    ".uasset": "unreal",
    ".zpr": "zbrush",
    ".ztl": "zbrush",
    ".spp": "substance_painter",
    ".sbs": "substance_designer",
    ".sbsar": "substance_designer",
    ".png": "it",
    ".exr": "it",
    ".tex": "it",
    ".usd": "usdview",
    ".usda": "usdview"
}